stages:
  prepare_data:
    cmd: python src/prepare_dataset.py
    deps:
      - src/prepare_dataset.py
      - data/raw/Limenitis_arthemis.csv
      - data/raw/Nymphalis_antiopa.csv
      - data/raw/Papilio_glaucus.csv
      - data/raw/Vanessa_atalanta.csv
      - data/raw/Vanessa_cardui.csv
    outs:
      - data/processed:
          cache: true

  train:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/processed
    outs:
      - models/butterfly_classifier.pth
    metrics:
      - metrics.json:
          cache: false
